package my_structs

type Car struct {
  DealerID                      string
  Type                          string
  Stock                         uint
  VIN                           string
  Year                          uint64
  Make                          string
  Model                         string
  ModelNumber                   string
  Body                          string
  Trim                          string
  Doors                         string
  ExteriorColor                 string
  InteriorColor                 string
  EngineCylinders               string
  EngineDisplacement            string
  Transmission                  string
  Miles                         string
  SellingPrice                  string
  MSRP                          string
  Certified                     string
  BookValue                     string
  CategorizedOptions            string
  Invoice                       string
  CityMPG                       string
  HighwayMPG                    string
  DateInStock                   string
  Internet_Price                string
  Description                   string
  Options                       string
  Style_Description             string
  Ext_Color_Generic             string
  Ext_Color_Code                string
  Int_Color_Generic             string
  Int_Color_Code                string
  Int_Upholstery                string
  Engine_Block_Type             string
  Engine_Aspiration_Type        string
  Engine_Description            string
  Transmission_Speed            string
  Transmission_Description      string
  Drivetrain                    string
  Fuel_Type                     string
  EPAClassification             string
  Wheelbase_Code                string
  Misc_Price1                   string
  Misc_Price2                   string
  Misc_Price3                   string
  Factory_Codes                 string
  MarketClass                   string
  PassengerCapacity             string
  ExtColorHexCode               string
  IntColorHexCode               string
  EngineDisplacementCubicInches string
  ImageList                     string
}
